---
# tasks file for ansible-unzip

- block:
    - name: Install unzip packages
      become: yes
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
        cache_valid_time: "{{ apt_cache_valid_time | default(omit) }}"
        install_recommends: no
      with_items:
        - "{{ unzip_packages }}"
        
  become: yes
  tags:
    - unzip
    - utilities